// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/mailer/manager.go
//
// Generated by this command:
//
//	mockgen -source=./internal/mailer/manager.go -destination=./internal/mailer/mocks/mock_manager.go
//

// Package mock_mailer is a generated GoMock package.
package mock_mailer

import (
	context "context"
	reflect "reflect"
	models "weather/internal/models"

	gomock "go.uber.org/mock/gomock"
)

// MockMailerStore is a mock of MailerStore interface.
type MockMailerStore struct {
	ctrl     *gomock.Controller
	recorder *MockMailerStoreMockRecorder
	isgomock struct{}
}

// MockMailerStoreMockRecorder is the mock recorder for MockMailerStore.
type MockMailerStoreMockRecorder struct {
	mock *MockMailerStore
}

// NewMockMailerStore creates a new mock instance.
func NewMockMailerStore(ctrl *gomock.Controller) *MockMailerStore {
	mock := &MockMailerStore{ctrl: ctrl}
	mock.recorder = &MockMailerStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailerStore) EXPECT() *MockMailerStoreMockRecorder {
	return m.recorder
}

// GetSubscribed mocks base method.
func (m *MockMailerStore) GetSubscribed(ctx context.Context) ([]models.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscribed", ctx)
	ret0, _ := ret[0].([]models.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscribed indicates an expected call of GetSubscribed.
func (mr *MockMailerStoreMockRecorder) GetSubscribed(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscribed", reflect.TypeOf((*MockMailerStore)(nil).GetSubscribed), ctx)
}
