version: '3'

dotenv:
  - .env

includes:
  mail:
    taskfile: ./mail-service/Taskfile.yml
    dir: ./mail-service
  weather:
    taskfile: ./weather-subscription-service/Taskfile.yml
    dir: ./weather-subscription-service

tasks:
  lint:
    desc: Run linters for both services
    cmds:
      - task: mail:lint
      - task: weather:lint

  build:
    desc: Build both mail-service and weather-service
    cmds:
      - task: mail:build
      - task: weather:build

  test:
    desc: Execute all tests (unit & integration) for both services
    cmds:
      - task: mail:test
      - task: weather:test

  up:
    desc: Start whole infrastructure (subscription-service, mail-service, DB, Redis, etc.)
    cmds:
      - docker network create app-net || true
      - task: mail:up
      - task: weather:up
    silent: true

  down:
    desc: Stop whole infrastructure (subscription-service, mail-service, DB, Redis, etc.)
    cmds:
      - task: mail:down
      - task: weather:down
      - docker network rm app-net || true
    silent: true

  run-mail:
    desc: Build & run only mail-service
    cmds:
      - task: mail:run

  run-weather:
    desc: Build & run only weather-service
    cmds:
      - task: weather:run

  proto-mailer:
    desc: Generate Go + gRPC code from your .proto files
    cmds:
      - mkdir -p pkg/protos/mailer
      - |
        protoc \
          -I protos \
          --go_out=pkg/protos/mailer \
          --go_opt=paths=source_relative \
          --go-grpc_out=pkg/protos/mailer \
          --go-grpc_opt=paths=source_relative \
          protos/mailer.proto