// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/weather/weather.go
//
// Generated by this command:
//
//	mockgen -source=./internal/weather/weather.go -destination=./internal/weather/mocks/mock_weather.go
//

// Package mock_weather is a generated GoMock package.
package mock_weather

import (
	context "context"
	reflect "reflect"
	models "weather/internal/models"
	weather "weather/internal/weather"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// LogError mocks base method.
func (m *MockLogger) LogError(msg string, fields ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "LogError", varargs...)
}

// LogError indicates an expected call of LogError.
func (mr *MockLoggerMockRecorder) LogError(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogError", reflect.TypeOf((*MockLogger)(nil).LogError), varargs...)
}

// LogInfo mocks base method.
func (m *MockLogger) LogInfo(msg string, fields ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "LogInfo", varargs...)
}

// LogInfo indicates an expected call of LogInfo.
func (mr *MockLoggerMockRecorder) LogInfo(msg any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogInfo", reflect.TypeOf((*MockLogger)(nil).LogInfo), varargs...)
}

// MockAPIInterface is a mock of APIInterface interface.
type MockAPIInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAPIInterfaceMockRecorder
	isgomock struct{}
}

// MockAPIInterfaceMockRecorder is the mock recorder for MockAPIInterface.
type MockAPIInterfaceMockRecorder struct {
	mock *MockAPIInterface
}

// NewMockAPIInterface creates a new mock instance.
func NewMockAPIInterface(ctrl *gomock.Controller) *MockAPIInterface {
	mock := &MockAPIInterface{ctrl: ctrl}
	mock.recorder = &MockAPIInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIInterface) EXPECT() *MockAPIInterfaceMockRecorder {
	return m.recorder
}

// GetCityWeather mocks base method.
func (m *MockAPIInterface) GetCityWeather(ctx context.Context, city string) (models.Weather, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCityWeather", ctx, city)
	ret0, _ := ret[0].(models.Weather)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCityWeather indicates an expected call of GetCityWeather.
func (mr *MockAPIInterfaceMockRecorder) GetCityWeather(ctx, city any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCityWeather", reflect.TypeOf((*MockAPIInterface)(nil).GetCityWeather), ctx, city)
}

// setNext mocks base method.
func (m *MockAPIInterface) setNext(arg0 weather.APIInterface) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "setNext", arg0)
}

// setNext indicates an expected call of setNext.
func (mr *MockAPIInterfaceMockRecorder) setNext(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "setNext", reflect.TypeOf((*MockAPIInterface)(nil).setNext), arg0)
}
