// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: mailer.proto

package mailer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Email struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToEmail       *string                `protobuf:"bytes,1,opt,name=to_email,json=toEmail" json:"to_email,omitempty"`
	Subject       *string                `protobuf:"bytes,2,opt,name=subject" json:"subject,omitempty"`
	Body          *string                `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Email) Reset() {
	*x = Email{}
	mi := &file_mailer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_mailer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_mailer_proto_rawDescGZIP(), []int{0}
}

func (x *Email) GetToEmail() string {
	if x != nil && x.ToEmail != nil {
		return *x.ToEmail
	}
	return ""
}

func (x *Email) GetSubject() string {
	if x != nil && x.Subject != nil {
		return *x.Subject
	}
	return ""
}

func (x *Email) GetBody() string {
	if x != nil && x.Body != nil {
		return *x.Body
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *uint64                `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Failed        *uint64                `protobuf:"varint,2,opt,name=failed" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_mailer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_mailer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_mailer_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetSuccess() uint64 {
	if x != nil && x.Success != nil {
		return *x.Success
	}
	return 0
}

func (x *Result) GetFailed() uint64 {
	if x != nil && x.Failed != nil {
		return *x.Failed
	}
	return 0
}

var File_mailer_proto protoreflect.FileDescriptor

const file_mailer_proto_rawDesc = "" +
	"\n" +
	"\fmailer.proto\x12\x06mailer\"P\n" +
	"\x05Email\x12\x19\n" +
	"\bto_email\x18\x01 \x01(\tR\atoEmail\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\":\n" +
	"\x06Result\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\x04R\asuccess\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\x04R\x06failed2;\n" +
	"\vMailService\x12,\n" +
	"\tSendEmail\x12\r.mailer.Email\x1a\x0e.mailer.Result(\x01B\x17Z\x15weather/protos/mailerb\beditionsp\xe8\a"

var (
	file_mailer_proto_rawDescOnce sync.Once
	file_mailer_proto_rawDescData []byte
)

func file_mailer_proto_rawDescGZIP() []byte {
	file_mailer_proto_rawDescOnce.Do(func() {
		file_mailer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mailer_proto_rawDesc), len(file_mailer_proto_rawDesc)))
	})
	return file_mailer_proto_rawDescData
}

var file_mailer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mailer_proto_goTypes = []any{
	(*Email)(nil),  // 0: mailer.Email
	(*Result)(nil), // 1: mailer.Result
}
var file_mailer_proto_depIdxs = []int32{
	0, // 0: mailer.MailService.SendEmail:input_type -> mailer.Email
	1, // 1: mailer.MailService.SendEmail:output_type -> mailer.Result
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mailer_proto_init() }
func file_mailer_proto_init() {
	if File_mailer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mailer_proto_rawDesc), len(file_mailer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mailer_proto_goTypes,
		DependencyIndexes: file_mailer_proto_depIdxs,
		MessageInfos:      file_mailer_proto_msgTypes,
	}.Build()
	File_mailer_proto = out.File
	file_mailer_proto_goTypes = nil
	file_mailer_proto_depIdxs = nil
}
