name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Fetch remote golangci-lint config
        run: |
          curl -fsSL https://raw.githubusercontent.com/fabl3ss/genesis-se-school-linter/refs/heads/main/.golangci.yaml \
          -o .golangci.yml
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
