name: Go Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Download dependencies
        run: go mod download

      - name: Run format check
        run: |
          go fmt ./...
          go vet ./...

      - name: Run Unit tests
        run: go test -v $(go list ./... | grep -v 'internal/api')

      - name: Run Integration tests
        run: go test -v ./internal/api/...
